version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - dnf install -y dnf-plugins-core
      - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - dnf install -y terraform

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Running Terraform FMT..."
      - terraform fmt -check || terraform fmt -write=true

      - echo "Validating Terraform configuration..."
      - terraform validate

      - echo "Generating Terraform plan..."
      - terraform plan -input=false -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform..."
      - terraform apply -input=false -auto-approve tfplan
      - echo "Terraform apply completed successfully."

artifacts:
  files:
    - "**/*"
